/*

 MAIN_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gb\gb sprite\blackmap.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define main_mapWidth 20
#define main_mapHeight 18
#define main_mapBank 0

extern unsigned char main_map[];

/* End of MAIN_MAP.H */
