/*

 MAPL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gb\gb sprite\blackmap.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapL1Width 20
#define mapL1Height 18
#define mapL1Bank 0

extern unsigned char mapL1[];

/* End of MAPL1.H */
